"""Generate the x.logo custom symbol (SF Symbols template v3, Regular-M only) from the official X mark.

The mark is made of straight edges only, so it is thickened by offsetting its polygons: the outline
grows by BOLDEN units on every side and the inner cut-out shrinks by as much, which keeps the shape.
Run: python3 scripts/make_x_logo_symbol.py
"""
from pathlib import Path
import math, re

root = Path(__file__).resolve().parents[1]
output = root / 'Infometrie/Resources/Assets.xcassets/x.logo.symbolset/x.logo.svg'

# Official X logo, 1200 x 1226.37 units.
LOGO = ('M714.163 519.284L1160.89 0H1055.03L667.137 450.887L357.328 0H0L468.492 681.821L0 1226.37H105.866'
        'L515.491 750.218L842.672 1226.37H1200L714.163 519.284ZM569.165 687.828L521.697 619.934L144.011 79.6944'
        'H306.615L611.412 515.685L658.88 583.579L1055.08 1150.3H892.476L569.165 687.828Z')
BOLDEN = 36.0   # logo units added to each side of every stroke; 0 keeps the official weight
CAP = 70.459    # template cap height at 100 pt
HEIGHT = 90.0   # glyph height, the size of square.grid.2x2 next to it in the feed tabs
BEARING = 4.0   # side bearing on each side


def polygons(path):
    """Split the path into point lists; it only uses M, L, H and Z."""
    result, current, point = [], [], (0.0, 0.0)
    for command, args in re.findall(r'([MLHZ])([^MLHZ]*)', path):
        numbers = [float(n) for n in re.findall(r'-?\d+(?:\.\d+)?', args)]
        if command == 'Z':
            if current[0] == current[-1]: current.pop()
            result.append(current); current = []
        elif command == 'H':
            point = (numbers[0], point[1]); current.append(point)
        else:
            for i in range(0, len(numbers), 2):
                point = (numbers[i], numbers[i + 1]); current.append(point)
    return result


def without_collinear(points):
    """Drop vertices lying on a straight edge: their offset lines would be parallel."""
    kept = []
    for i, b in enumerate(points):
        a, c = points[i - 1], points[(i + 1) % len(points)]
        cross = (b[0] - a[0]) * (c[1] - b[1]) - (b[1] - a[1]) * (c[0] - b[0])
        if abs(cross) > 1e-3 * math.dist(a, b) * math.dist(b, c): kept.append(b)
    return kept


def offset(points, distance):
    """Move every edge outward by distance (inward when negative), joining edges with miters."""
    area = sum(a[0] * b[1] - b[0] * a[1] for a, b in zip(points, points[1:] + points[:1]))
    sign = 1 if area > 0 else -1
    lines = []
    for a, b in zip(points, points[1:] + points[:1]):
        dx, dy = b[0] - a[0], b[1] - a[1]
        length = math.hypot(dx, dy)
        nx, ny = sign * dy / length * distance, -sign * dx / length * distance
        lines.append(((a[0] + nx, a[1] + ny), (dx, dy)))
    moved = []
    for (p, r), (q, s) in zip(lines[-1:] + lines[:-1], lines):
        denominator = r[0] * s[1] - r[1] * s[0]
        t = ((q[0] - p[0]) * s[1] - (q[1] - p[1]) * s[0]) / denominator
        moved.append((p[0] + t * r[0], p[1] + t * r[1]))
    return moved


def f(value):
    return f'{value:.3f}'.rstrip('0').rstrip('.')


outline, cutout = (without_collinear(p) for p in polygons(LOGO))
shapes = [offset(outline, BOLDEN), offset(cutout, -BOLDEN)]
xs = [x for shape in shapes for x, _ in shape]; ys = [y for shape in shapes for _, y in shape]
scale = HEIGHT / (max(ys) - min(ys))
top = -CAP / 2 - HEIGHT / 2  # centered on the middle of the cap height; y grows downward
path = ''.join('M' + 'L'.join(f'{f(BEARING + (x - min(xs)) * scale)} {f(top + (y - min(ys)) * scale)}' for x, y in shape) + 'Z'
               for shape in shapes)
left = 1400.0
right = left + 2 * BEARING + (max(xs) - min(xs)) * scale
guide = 'fill:none;stroke:#27AAE1;opacity:1;stroke-width:0.5;'
output.write_text(f'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="3300" height="2200">
 <!--glyph: "x.logo", point size: 100.0, X logo mark, generated by scripts/make_x_logo_symbol.py-->
 <g id="Notes">
  <rect height="2200" id="artboard" style="fill:white;opacity:1" width="3300" x="0" y="0"/>
  <text id="template-version" style="stroke:none;fill:black;font-family:sans-serif;font-size:13;text-anchor:end;" transform="matrix(1 0 0 1 3036 1933)">Template v.3.0</text>
 </g>
 <g id="Guides">
  <line id="Baseline-S" style="{guide}" x1="263" x2="3036" y1="696" y2="696"/>
  <line id="Capline-S" style="{guide}" x1="263" x2="3036" y1="625.541" y2="625.541"/>
  <line id="Baseline-M" style="{guide}" x1="263" x2="3036" y1="1126" y2="1126"/>
  <line id="Capline-M" style="{guide}" x1="263" x2="3036" y1="1055.54" y2="1055.54"/>
  <line id="Baseline-L" style="{guide}" x1="263" x2="3036" y1="1556" y2="1556"/>
  <line id="Capline-L" style="{guide}" x1="263" x2="3036" y1="1485.54" y2="1485.54"/>
  <line id="left-margin-Regular-M" style="{guide}" x1="{f(left)}" x2="{f(left)}" y1="1030.79" y2="1150.12"/>
  <line id="right-margin-Regular-M" style="{guide}" x1="{f(right)}" x2="{f(right)}" y1="1030.79" y2="1150.12"/>
 </g>
 <g id="Symbols">
  <g id="Regular-M" transform="matrix(1 0 0 1 {f(left)} 1126)">
   <path d="{path}"/>
  </g>
 </g>
</svg>
''')
print(f'x.logo: bolden {f(BOLDEN)}, {len(shapes[0])} + {len(shapes[1])} points, width {f(right - left)}')
